/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Gestao.Equipa;
import Gestao.Escola;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rui
 */
public class CriarCompeticoes extends javax.swing.JFrame implements Observer {

    private AssociacaoEscolasFutebol a;

    /**
     * Creates new form CriarCompeticoes
     */
    public CriarCompeticoes(AssociacaoEscolasFutebol a) {
        this.a = a;
        this.a.addObserver(this);
        initComponents();
        this.setVisible(true);
        jList3.setModel(new DefaultListModel());
        jList4.setModel(new DefaultListModel());
        jList6.setModel(new DefaultListModel());
        jList5.setModel(new DefaultListModel());
        for (Escola escola : a.getDAOEscola().values()) {
            Escola_ComboBox1.addItem(escola.getNome());
            Escola_ComboBox2.addItem(escola.getNome());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        TabbedPane = new javax.swing.JTabbedPane();
        CriarJogo_Panel = new javax.swing.JPanel();
        GerirEquipa_Panel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Equipa1_TextField = new javax.swing.JTextField();
        ProcurarEquipa1_Button = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        EquipaSelecionada_Label1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Escola_ComboBox1 = new javax.swing.JComboBox();
        GerirEquipa_Panel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Equipa2_TextField = new javax.swing.JTextField();
        ProcurarEquipa2_Button = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        EquipaSelecionada_Label2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Escola_ComboBox2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        CriarCampeonato_Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NomeCampeonato_TextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EscalaoCampeonato_ComboBox = new javax.swing.JComboBox();
        CriarCampeonato_Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jList6 = new javax.swing.JList();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        CriarTorneio_Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        NomeTorneio_TextField = new javax.swing.JTextField();
        EscalaoTorneio_ComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TipoTorneio_ComboBox = new javax.swing.JComboBox();
        CriarTorneio_Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        VoltarMenuPrincipal_Button6 = new javax.swing.JButton();
        CriarJogoCompeticoes_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GerirEquipa_Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipa 1:"));

        jLabel14.setText("Equipa:");

        ProcurarEquipa1_Button.setText("Procurar Equipa");
        ProcurarEquipa1_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarEquipa1_ButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Equipa Selecionada:");

        EquipaSelecionada_Label1.setText("nenhuma");

        jLabel18.setText("Escola:");

        javax.swing.GroupLayout GerirEquipa_Panel1Layout = new javax.swing.GroupLayout(GerirEquipa_Panel1);
        GerirEquipa_Panel1.setLayout(GerirEquipa_Panel1Layout);
        GerirEquipa_Panel1Layout.setHorizontalGroup(
            GerirEquipa_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerirEquipa_Panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GerirEquipa_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GerirEquipa_Panel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Equipa1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GerirEquipa_Panel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EquipaSelecionada_Label1))
                    .addComponent(ProcurarEquipa1_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(GerirEquipa_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Escola_ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GerirEquipa_Panel1Layout.setVerticalGroup(
            GerirEquipa_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerirEquipa_Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GerirEquipa_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Escola_ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GerirEquipa_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Equipa1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(ProcurarEquipa1_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GerirEquipa_Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(EquipaSelecionada_Label1))
                .addContainerGap())
        );

        GerirEquipa_Panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipa 2:"));

        jLabel16.setText("Equipa:");

        ProcurarEquipa2_Button.setText("Procurar Equipa");
        ProcurarEquipa2_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarEquipa2_ButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("Equipa Selecionada:");

        EquipaSelecionada_Label2.setText("nenhuma");

        jLabel19.setText("Escola:");

        javax.swing.GroupLayout GerirEquipa_Panel2Layout = new javax.swing.GroupLayout(GerirEquipa_Panel2);
        GerirEquipa_Panel2.setLayout(GerirEquipa_Panel2Layout);
        GerirEquipa_Panel2Layout.setHorizontalGroup(
            GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerirEquipa_Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GerirEquipa_Panel2Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Equipa2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GerirEquipa_Panel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Escola_ComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(GerirEquipa_Panel2Layout.createSequentialGroup()
                        .addGroup(GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProcurarEquipa2_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(GerirEquipa_Panel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EquipaSelecionada_Label2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        GerirEquipa_Panel2Layout.setVerticalGroup(
            GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GerirEquipa_Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Escola_ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Equipa2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProcurarEquipa2_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(GerirEquipa_Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(EquipaSelecionada_Label2))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data e Local:"));

        jLabel1.setText("Data:");

        jLabel2.setText("Campo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton1.setText("Criar Jogo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CriarJogo_PanelLayout = new javax.swing.GroupLayout(CriarJogo_Panel);
        CriarJogo_Panel.setLayout(CriarJogo_PanelLayout);
        CriarJogo_PanelLayout.setHorizontalGroup(
            CriarJogo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarJogo_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriarJogo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GerirEquipa_Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GerirEquipa_Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarJogo_PanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );

        CriarJogo_PanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {GerirEquipa_Panel1, GerirEquipa_Panel2});

        CriarJogo_PanelLayout.setVerticalGroup(
            CriarJogo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarJogo_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriarJogo_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GerirEquipa_Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GerirEquipa_Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        TabbedPane.addTab("Criar Jogo", CriarJogo_Panel);

        jLabel3.setText("Nome Campeonato:");

        jLabel4.setText("Escalão:");

        EscalaoCampeonato_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PreEscolaA", "PreEscolaB", "EscolaA", "EscolaB", "InfantisA", "InfantisB", "IniciadosA", "IniciadosB", "MinisA", "MinisB" }));
        EscalaoCampeonato_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EscalaoCampeonato_ComboBoxItemStateChanged(evt);
            }
        });

        CriarCampeonato_Button.setText("Criar Campeonato");
        CriarCampeonato_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarCampeonato_ButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipas selecionadas:"));

        jList5.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jList5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipas selecionáveis:"));

        jList6.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jList6);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
        );

        jButton10.setText("Todas >");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText(">");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("<");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Todas <");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Data de Inicio:");

        javax.swing.GroupLayout CriarCampeonato_PanelLayout = new javax.swing.GroupLayout(CriarCampeonato_Panel);
        CriarCampeonato_Panel.setLayout(CriarCampeonato_PanelLayout);
        CriarCampeonato_PanelLayout.setHorizontalGroup(
            CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarCampeonato_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarCampeonato_PanelLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CriarCampeonato_PanelLayout.createSequentialGroup()
                        .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeCampeonato_TextField)
                            .addComponent(EscalaoCampeonato_ComboBox, 0, 188, Short.MAX_VALUE)
                            .addComponent(jFormattedTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CriarCampeonato_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        CriarCampeonato_PanelLayout.setVerticalGroup(
            CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarCampeonato_PanelLayout.createSequentialGroup()
                .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarCampeonato_PanelLayout.createSequentialGroup()
                        .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(NomeCampeonato_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EscalaoCampeonato_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(CriarCampeonato_PanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CriarCampeonato_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarCampeonato_PanelLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13)
                        .addGap(99, 99, 99))
                    .addGroup(CriarCampeonato_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        TabbedPane.addTab("Criar Campeonato", CriarCampeonato_Panel);

        jLabel5.setText("Nome Torneio:");

        EscalaoTorneio_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PreEscolaA", "PreEscolaB", "EscolaA", "EscolaB", "InfantisA", "InfantisB", "IniciadosA", "IniciadosB", "MinisA", "MinisB" }));
        EscalaoTorneio_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EscalaoTorneio_ComboBoxItemStateChanged(evt);
            }
        });
        EscalaoTorneio_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscalaoTorneio_ComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Escalão:");

        jButton6.setText("Todas >");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(">");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("<");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Todas <");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo Torneio:");

        TipoTorneio_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eliminatórias", "Dupla-Eliminatórias" }));
        TipoTorneio_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoTorneio_ComboBoxActionPerformed(evt);
            }
        });

        CriarTorneio_Button.setText("Criar Torneio");
        CriarTorneio_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarTorneio_ButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipas selecionáveis:"));

        jScrollPane4.setViewportView(jList3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipas selecionadas:"));

        jScrollPane5.setViewportView(jList4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );

        jLabel9.setText("Data de Inicio:");

        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CriarTorneio_PanelLayout = new javax.swing.GroupLayout(CriarTorneio_Panel);
        CriarTorneio_Panel.setLayout(CriarTorneio_PanelLayout);
        CriarTorneio_PanelLayout.setHorizontalGroup(
            CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeTorneio_TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EscalaoTorneio_ComboBox, 0, 147, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TipoTorneio_ComboBox, 0, 1, Short.MAX_VALUE))
                            .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(CriarTorneio_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        CriarTorneio_PanelLayout.setVerticalGroup(
            CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TipoTorneio_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeTorneio_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CriarTorneio_Button))
                    .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EscalaoTorneio_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriarTorneio_PanelLayout.createSequentialGroup()
                        .addGroup(CriarTorneio_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriarTorneio_PanelLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addGap(109, 109, 109))))
        );

        TabbedPane.addTab("Criar Torneio", CriarTorneio_Panel);

        VoltarMenuPrincipal_Button6.setText("Voltar Menu Principal");
        VoltarMenuPrincipal_Button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarMenuPrincipal_Button6ActionPerformed(evt);
            }
        });

        CriarJogoCompeticoes_Label.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        CriarJogoCompeticoes_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CriarJogoCompeticoes_Label.setText("Criar Jogo/Competições:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CriarJogoCompeticoes_Label)
                    .addComponent(VoltarMenuPrincipal_Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(CriarJogoCompeticoes_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoltarMenuPrincipal_Button6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarMenuPrincipal_Button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarMenuPrincipal_Button6ActionPerformed
        new Gestor(a);
        this.dispose();
    }//GEN-LAST:event_VoltarMenuPrincipal_Button6ActionPerformed

    private void ProcurarEquipa2_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarEquipa2_ButtonActionPerformed
        // TODO add your handling code here:
        Equipa equipa = a.getEquipa(Escola_ComboBox2.getSelectedItem().toString(), Escola_ComboBox2.getSelectedItem().toString() + "-" + Equipa2_TextField.getText());
        if (equipa != null) {
            EquipaSelecionada_Label2.setText(Equipa2_TextField.getText());
        }
    }//GEN-LAST:event_ProcurarEquipa2_ButtonActionPerformed

    private void ProcurarEquipa1_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarEquipa1_ButtonActionPerformed
        // TODO add your handling code here:
        Equipa equipa = a.getEquipa(Escola_ComboBox1.getSelectedItem().toString(), Escola_ComboBox1.getSelectedItem().toString() + "-" + Equipa1_TextField.getText());
        if (equipa != null) {
            EquipaSelecionada_Label1.setText(Equipa1_TextField.getText());
        }
    }//GEN-LAST:event_ProcurarEquipa1_ButtonActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList6.getModel();
        DefaultListModel model1 = (DefaultListModel) jList5.getModel();
        model1.addElement(jList6.getModel().getElementAt(jList6.getSelectedIndex()));
        model.remove(jList6.getSelectedIndex());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void EscalaoCampeonato_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EscalaoCampeonato_ComboBoxItemStateChanged
        // TODO add your handling code here:
        jList6.setModel(new DefaultListModel());
        DefaultListModel model = (DefaultListModel) jList6.getModel();
        for (Escola escola : a.getDAOEscola().values()) {
            for (Equipa equipa : escola.getEquipas(escola.getCod_Escola(), "Escalao." + EscalaoCampeonato_ComboBox.getSelectedItem().toString())) {
                model.addElement(equipa.getCodEquipa());
            }
        }
    }

    @Override
    public void update(Observable o, Object arg) {

    }//GEN-LAST:event_EscalaoCampeonato_ComboBoxItemStateChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList6.getModel();
        DefaultListModel model1 = (DefaultListModel) jList5.getModel();
        model.addElement(jList5.getModel().getElementAt(jList5.getSelectedIndex()));
        model1.remove(jList5.getSelectedIndex());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList6.getModel();
        DefaultListModel model1 = (DefaultListModel) jList5.getModel();

        while (model.size() > 0) {
            model1.addElement(jList6.getModel().getElementAt(0));
            model.remove(0);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList6.getModel();
        DefaultListModel model1 = (DefaultListModel) jList5.getModel();
        while (model1.size() > 0) {
            model.addElement(jList5.getModel().getElementAt(0));
            model1.remove(0);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void CriarCampeonato_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarCampeonato_ButtonActionPerformed
        // TODO add your handling code here:
        Collection<String> equipas = new ArrayList<String>();
        DefaultListModel model1 = (DefaultListModel) jList5.getModel();
        for (int i = 0; i < model1.size(); i++) {
            equipas.add((String) jList5.getModel().getElementAt(i));
        }
        try {
            if (equipas.size()>=2 && equipas.size()%2==0) {
                a.CriarCompeticao(NomeCampeonato_TextField.getText(), "Escalao." + EscalaoCampeonato_ComboBox.getSelectedItem().toString(), equipas, 0, "", jFormattedTextField2.getText());
                JOptionPane.showMessageDialog(null, "Campeonato inserido com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(null, "Numero de Equipas insuficiente", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_CriarCampeonato_ButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Collection<String> equipas = new ArrayList<String>();
        equipas.add(Escola_ComboBox1.getSelectedItem().toString() + "-" + EquipaSelecionada_Label1.getText());
        equipas.add(Escola_ComboBox2.getSelectedItem().toString() + "-" + EquipaSelecionada_Label2.getText());
        try {
            a.CriarCompeticao(EquipaSelecionada_Label1.getText() + "-" + EquipaSelecionada_Label2.getText(), a.getDAOEscola().get(Escola_ComboBox1.getSelectedItem().toString()).getEquipa(Escola_ComboBox1.getSelectedItem().toString() + "-" + EquipaSelecionada_Label1.getText()).getEscalao().toString(), equipas, 1, "Eliminatórias", jFormattedTextField1.getText());
            JOptionPane.showMessageDialog(null, "Jogo inserido com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void EscalaoTorneio_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscalaoTorneio_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EscalaoTorneio_ComboBoxActionPerformed

    private void EscalaoTorneio_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EscalaoTorneio_ComboBoxItemStateChanged
        // TODO add your handling code here:
        jList3.setModel(new DefaultListModel());
        DefaultListModel model = (DefaultListModel) jList3.getModel();
        for (Escola escola : a.getDAOEscola().values()) {
            for (Equipa equipa : escola.getEquipas(escola.getCod_Escola(), "Escalao." + EscalaoTorneio_ComboBox.getSelectedItem().toString())) {
                model.addElement(equipa.getCodEquipa());
            }
        }
    }//GEN-LAST:event_EscalaoTorneio_ComboBoxItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList3.getModel();
        DefaultListModel model1 = (DefaultListModel) jList4.getModel();

        while (model.size() > 0) {
            model1.addElement(jList3.getModel().getElementAt(0));
            model.remove(0);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList3.getModel();
        DefaultListModel model1 = (DefaultListModel) jList4.getModel();
        model1.addElement(jList3.getModel().getElementAt(jList3.getSelectedIndex()));
        model.remove(jList3.getSelectedIndex());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList3.getModel();
        DefaultListModel model1 = (DefaultListModel) jList4.getModel();
        model.addElement(jList4.getModel().getElementAt(jList4.getSelectedIndex()));
        model1.remove(jList4.getSelectedIndex());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jList3.getModel();
        DefaultListModel model1 = (DefaultListModel) jList4.getModel();
        while (model1.size() > 0) {
            model.addElement(jList4.getModel().getElementAt(0));
            model1.remove(0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void CriarTorneio_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarTorneio_ButtonActionPerformed
        // TODO add your handling code here:
        Collection<String> equipas = new ArrayList<String>();
        DefaultListModel model1 = (DefaultListModel) jList4.getModel();
        for (int i = 0; i < model1.size(); i++) {
            equipas.add((String) jList4.getModel().getElementAt(i));
        }
        if ((equipas.size() & -equipas.size()) == equipas.size()&& equipas.size()!=0) {
            try {
                a.CriarCompeticao(NomeTorneio_TextField.getText(), "Escalao." + EscalaoTorneio_ComboBox.getSelectedItem().toString(), equipas, 1, TipoTorneio_ComboBox.getSelectedItem().toString(), jFormattedTextField3.getText());
                JOptionPane.showMessageDialog(null, "Torneio inserido com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Numero de Equipas insuficiente", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_CriarTorneio_ButtonActionPerformed

    private void TipoTorneio_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoTorneio_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoTorneio_ComboBoxActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarCampeonato_Button;
    private javax.swing.JPanel CriarCampeonato_Panel;
    private javax.swing.JLabel CriarJogoCompeticoes_Label;
    private javax.swing.JPanel CriarJogo_Panel;
    private javax.swing.JButton CriarTorneio_Button;
    private javax.swing.JPanel CriarTorneio_Panel;
    private javax.swing.JTextField Equipa1_TextField;
    private javax.swing.JTextField Equipa2_TextField;
    private javax.swing.JLabel EquipaSelecionada_Label1;
    private javax.swing.JLabel EquipaSelecionada_Label2;
    private javax.swing.JComboBox EscalaoCampeonato_ComboBox;
    private javax.swing.JComboBox EscalaoTorneio_ComboBox;
    private javax.swing.JComboBox Escola_ComboBox1;
    private javax.swing.JComboBox Escola_ComboBox2;
    private javax.swing.JPanel GerirEquipa_Panel1;
    private javax.swing.JPanel GerirEquipa_Panel2;
    private javax.swing.JTextField NomeCampeonato_TextField;
    private javax.swing.JTextField NomeTorneio_TextField;
    private javax.swing.JButton ProcurarEquipa1_Button;
    private javax.swing.JButton ProcurarEquipa2_Button;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JComboBox TipoTorneio_ComboBox;
    private javax.swing.JButton VoltarMenuPrincipal_Button6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JList jList5;
    private javax.swing.JList jList6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables

}
