/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Competicao.Campo;
import Competicao.Competicao;
import Competicao.Jogo;
import Competicao.Jornada;
import Competicao.Torneio;
import java.sql.SQLException;
import java.util.Collection;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Rui
 */
public class GerirJogos extends javax.swing.JFrame implements Observer {

    private AssociacaoEscolasFutebol a;

    /**
     * Creates new form GerirJogos
     */
    public GerirJogos(AssociacaoEscolasFutebol a) {
        this.a = a;
        this.a.addObserver(this);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Gestor_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Escalao_ComboBox = new javax.swing.JComboBox();
        Competicao_ComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Jornada_ComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        GravarAlteracoes_Button = new javax.swing.JButton();
        JogoAmigavel_CheckBox = new javax.swing.JCheckBox();
        VoltarMenuPrincipal_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Gestor_Label.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        Gestor_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gestor_Label.setText("Gerir Jogos:");

        jLabel1.setText("Competição:");

        jLabel2.setText("Escalão:");

        Escalao_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PreEscolaA", "PreEscolaB", "MinisA", "MinisB", "EscolaA", "EscolaB", "InfantisA", "InfantisB", "IniciadosA", "IniciadosB" }));
        Escalao_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Escalao_ComboBoxItemStateChanged(evt);
            }
        });

        Competicao_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Competicao_ComboBoxItemStateChanged(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Calendário:"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipa casa", "Equipa fora", "Data", "Campo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFillsViewportHeight(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        jLabel3.setText("Jornada:");

        Jornada_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Jornada_ComboBoxItemStateChanged(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Data:"));

        jLabel4.setText("Nova Data:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterar Campo:"));

        jLabel5.setText("Novo Campo:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GravarAlteracoes_Button.setText("Gravar Alterações");
        GravarAlteracoes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GravarAlteracoes_ButtonActionPerformed(evt);
            }
        });

        JogoAmigavel_CheckBox.setText("Jogo Amigável?");
        JogoAmigavel_CheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JogoAmigavel_CheckBoxMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JogoAmigavel_CheckBoxMousePressed(evt);
            }
        });
        JogoAmigavel_CheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                JogoAmigavel_CheckBoxStateChanged(evt);
            }
        });
        JogoAmigavel_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JogoAmigavel_CheckBoxItemStateChanged(evt);
            }
        });
        JogoAmigavel_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JogoAmigavel_CheckBoxActionPerformed(evt);
            }
        });
        JogoAmigavel_CheckBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                JogoAmigavel_CheckBoxPropertyChange(evt);
            }
        });

        VoltarMenuPrincipal_Button.setText("Voltar Menu Principal");
        VoltarMenuPrincipal_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarMenuPrincipal_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GravarAlteracoes_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gestor_Label)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Escalao_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Competicao_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Jornada_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(JogoAmigavel_CheckBox)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(VoltarMenuPrincipal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Gestor_Label)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Escalao_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JogoAmigavel_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Competicao_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Jornada_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(GravarAlteracoes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VoltarMenuPrincipal_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JogoAmigavel_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JogoAmigavel_CheckBoxActionPerformed
        if (JogoAmigavel_CheckBox.isSelected()) {
            Jornada_ComboBox.setEnabled(false);
            Competicao_ComboBox.setEnabled(false);
        } else {
            Jornada_ComboBox.setEnabled(false);
            Competicao_ComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_JogoAmigavel_CheckBoxActionPerformed

    private void JogoAmigavel_CheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_JogoAmigavel_CheckBoxStateChanged

    }//GEN-LAST:event_JogoAmigavel_CheckBoxStateChanged

    private void JogoAmigavel_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JogoAmigavel_CheckBoxItemStateChanged

    }//GEN-LAST:event_JogoAmigavel_CheckBoxItemStateChanged

    private void JogoAmigavel_CheckBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_JogoAmigavel_CheckBoxPropertyChange

    }//GEN-LAST:event_JogoAmigavel_CheckBoxPropertyChange

    private void JogoAmigavel_CheckBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JogoAmigavel_CheckBoxMousePressed

    }//GEN-LAST:event_JogoAmigavel_CheckBoxMousePressed

    private void JogoAmigavel_CheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JogoAmigavel_CheckBoxMouseClicked

    }//GEN-LAST:event_JogoAmigavel_CheckBoxMouseClicked

    private void Escalao_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Escalao_ComboBoxItemStateChanged
        // TODO add your handling code here:
        Competicao_ComboBox.removeAllItems();
        String escalao;
        for (Competicao c : a.getDAOCompeticao().values()) {
            escalao = c.getEscalao().getClass().toString();
            if (escalao.equals("class Escalao." + Escalao_ComboBox.getSelectedItem().toString())) {
                if (c.getClass().getName().equals("Competicao.Campeonato")) {
                    Competicao_ComboBox.addItem(c.getNome());
                }
                if ((c instanceof Torneio)) {
                    Competicao_ComboBox.addItem(c.getNome());
                }
            }

        }
    }//GEN-LAST:event_Escalao_ComboBoxItemStateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here
        jComboBox1.removeAllItems();
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        String data = (String) jTable1.getValueAt(row, col);
        String campo[]=data.split("-");
        if (a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()) != null) {
            for (Campo d : a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()).getCampo().values(campo[0])) {
                jComboBox1.addItem(d.getCodigo());
            }
        } else {
            for (Campo d : a.getCompeticao("Escalao." + Escalao_ComboBox.getSelectedItem().toString()).getCampo().values(campo[0])) {
                jComboBox1.addItem(d.getCodigo());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void Competicao_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Competicao_ComboBoxItemStateChanged
        // TODO add your handling code here:
        Jornada_ComboBox.removeAllItems();
        if(Competicao_ComboBox.getSelectedIndex()>-1){
        if (a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()) != null) {
            int max_jornadas = a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()).getDAOJornada().size(Competicao_ComboBox.getSelectedItem().toString());
            for (int i = 1; i <= max_jornadas; i++) {
                Jornada_ComboBox.addItem(Integer.toString(i));
            }
        } else {
            int max_jornadas = a.getCompeticao("Escalao."+Escalao_ComboBox.getSelectedItem().toString()).getDAOJornada().size("Escalao."+Escalao_ComboBox.getSelectedItem().toString());
            for (int i = 1; i <= max_jornadas; i++) {
                Jornada_ComboBox.addItem(Integer.toString(i));
            }
        }
        }

    }//GEN-LAST:event_Competicao_ComboBoxItemStateChanged

    private void Jornada_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Jornada_ComboBoxItemStateChanged
        // TODO add your handling code here:
        clearTable(jTable1);
        if(Jornada_ComboBox.getSelectedIndex()>-1){
            if (a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()) != null) {
                Collection<Jogo> jogos = a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()).getJogos().
                        values(Competicao_ComboBox.getSelectedItem().toString(),Competicao_ComboBox.getSelectedItem().toString()+"_"+(Jornada_ComboBox.getSelectedIndex()+1));
                int i=0;
               Jornada jor=a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()).getDAOJornada().get(Competicao_ComboBox.getSelectedItem().toString()+"_"+(Jornada_ComboBox.getSelectedIndex()+1));
                if(jogos != null) {
                    for(Jogo jogo: jogos) {
                        if (jogo.getGolo1()== -1 || jogo.getGolo2()== -1) {
                             jTable1.setValueAt(jogo.getEquipa1(), i, 0);
                             jTable1.setValueAt(jogo.getEquipa2(), i, 1);
                             jTable1.setValueAt(jor.getDate(), i, 2);
                             jTable1.setValueAt(jogo.getCod_Campo(),i,3);
                             i++;
                    }
                }
            }
            }else{
                 Collection<Jogo> jogos = a.getCompeticao("Escalao."+Escalao_ComboBox.getSelectedItem().toString()).getJogos().
                        values("Escalao."+Escalao_ComboBox.getSelectedItem().toString(),"Escalao."+Escalao_ComboBox.getSelectedItem().toString()+(Jornada_ComboBox.getSelectedIndex()));
                int i=0;
                Jornada jor=a.getCompeticao("Escalao."+Escalao_ComboBox.getSelectedItem().toString()).getDAOJornada().get("Escalao."+Escalao_ComboBox.getSelectedItem().toString()+(Jornada_ComboBox.getSelectedIndex()));
                if(jogos != null) {
                    for(Jogo jogo: jogos) {
                        if (jogo.getGolo1()== -1 || jogo.getGolo2()== -1) {
                             jTable1.setValueAt(jogo.getEquipa1(), i, 0);
                             jTable1.setValueAt(jogo.getEquipa2(), i, 1);
                             jTable1.setValueAt(jor.getDate(), i, 2);
                             jTable1.setValueAt(jogo.getCod_Campo(),i,3);
                             i++;
                    }
                }
            }
        }
        }
    }//GEN-LAST:event_Jornada_ComboBoxItemStateChanged

    private void GravarAlteracoes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GravarAlteracoes_ButtonActionPerformed
        // TODO add your handling code here:
        if (a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()) != null) {
            try {
               if(a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()).getOcupacao().verificaOcupacao(4,jTextField1.getText(), jComboBox1.getSelectedItem().toString())>0){
                  a.getCompeticao(Competicao_ComboBox.getSelectedItem().toString()).getOcupacao().validaOcupacao(4, jTextField1.getText(), jComboBox1.getSelectedItem().toString());
                  jTable1.setValueAt(jTextField1.getText(), jTable1.getSelectedRow(), 2);
                  JOptionPane.showMessageDialog(null, "Data e Jogo modificados com sucesso", "OK", JOptionPane.INFORMATION_MESSAGE);
               }else{
                   JOptionPane.showMessageDialog(null, "Campo indisponivel", "ERRO", JOptionPane.ERROR_MESSAGE);
               }  
                   } catch (SQLException ex) {
                Logger.getLogger(GerirJogos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_GravarAlteracoes_ButtonActionPerformed

    private void VoltarMenuPrincipal_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarMenuPrincipal_ButtonActionPerformed
        // TODO add your handling code here:
         new Gestor(a);
        this.dispose();
    }//GEN-LAST:event_VoltarMenuPrincipal_ButtonActionPerformed

     public static void clearTable(JTable table) {
        for (int i = 0; i < table.getRowCount(); i++) {
            for (int j = 0; j < table.getColumnCount(); j++) {
                table.setValueAt("", i, j);
            }
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Competicao_ComboBox;
    private javax.swing.JComboBox Escalao_ComboBox;
    private javax.swing.JLabel Gestor_Label;
    private javax.swing.JButton GravarAlteracoes_Button;
    private javax.swing.JCheckBox JogoAmigavel_CheckBox;
    private javax.swing.JComboBox Jornada_ComboBox;
    private javax.swing.JButton VoltarMenuPrincipal_Button;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
