/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author Rui Mendes
 */
public class Gestor extends javax.swing.JFrame {
    private AssociacaoEscolasFutebol a;
    /**
     * Creates new form Gestor
     */
    public Gestor(AssociacaoEscolasFutebol a) {
        this.a = a;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Gestor_Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GerirJogos_Button = new javax.swing.JButton();
        GerirEscolas_Button = new javax.swing.JButton();
        Consultar_Button = new javax.swing.JButton();
        GerirJuizes_Button = new javax.swing.JButton();
        CriarCompeticoes_Button = new javax.swing.JButton();
        Logout_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Associação de Escolas de Futebol - Época 13/14");

        Gestor_Label.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        Gestor_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Gestor_Label.setText("Autenticado como: Gestor");

        GerirJogos_Button.setText("Gerir Jogos");
        GerirJogos_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerirJogos_ButtonActionPerformed(evt);
            }
        });

        GerirEscolas_Button.setText("Gerir Escolas e Equipas");
        GerirEscolas_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerirEscolas_ButtonActionPerformed(evt);
            }
        });

        Consultar_Button.setText("Consultar");
        Consultar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_ButtonActionPerformed(evt);
            }
        });

        GerirJuizes_Button.setText("Gerir Juízes");
        GerirJuizes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerirJuizes_ButtonActionPerformed(evt);
            }
        });

        CriarCompeticoes_Button.setText("Criar Jogo/Competições");
        CriarCompeticoes_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarCompeticoes_ButtonActionPerformed(evt);
            }
        });

        Logout_Button.setText("Logout");
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logout_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(CriarCompeticoes_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GerirJuizes_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GerirJogos_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Consultar_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GerirEscolas_Button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Consultar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GerirEscolas_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GerirJogos_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GerirJuizes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CriarCompeticoes_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gestor_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Gestor_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerirEscolas_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerirEscolas_ButtonActionPerformed
        new GerirEscolasEquipas(this.a);
        this.dispose();
    }//GEN-LAST:event_GerirEscolas_ButtonActionPerformed

    private void Consultar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_ButtonActionPerformed
        new Consultar(this.a);
        this.dispose();
    }//GEN-LAST:event_Consultar_ButtonActionPerformed

    private void GerirJuizes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerirJuizes_ButtonActionPerformed
        new GerirJuizes(this.a);
        this.dispose();
    }//GEN-LAST:event_GerirJuizes_ButtonActionPerformed

    private void CriarCompeticoes_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarCompeticoes_ButtonActionPerformed
        new CriarCompeticoes(this.a);
        this.dispose();
    }//GEN-LAST:event_CriarCompeticoes_ButtonActionPerformed

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
        /*new Login(this.a);*/
        this.dispose();
    }//GEN-LAST:event_Logout_ButtonActionPerformed

    private void GerirJogos_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerirJogos_ButtonActionPerformed
        new GerirJogos(this.a);
        this.dispose();
    }//GEN-LAST:event_GerirJogos_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar_Button;
    private javax.swing.JButton CriarCompeticoes_Button;
    private javax.swing.JButton GerirEscolas_Button;
    private javax.swing.JButton GerirJogos_Button;
    private javax.swing.JButton GerirJuizes_Button;
    private javax.swing.JLabel Gestor_Label;
    private javax.swing.JButton Logout_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
