/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author Rui Mendes
 */
public class Juiz extends javax.swing.JFrame {
    private AssociacaoEscolasFutebol a;
    /**
     * Creates new form Juíz
     */
    public Juiz(AssociacaoEscolasFutebol a) {
        this.a = a;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Juiz_Label = new javax.swing.JLabel();
        Consultar_Button = new javax.swing.JButton();
        GerirEscolas_Button = new javax.swing.JButton();
        Logout_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Associação de Escolas de Futebol - Época 13/14");

        Juiz_Label.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        Juiz_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Juiz_Label.setText("Autenticado como: Juíz");

        Consultar_Button.setText("Consultar");
        Consultar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Consultar_ButtonActionPerformed(evt);
            }
        });

        GerirEscolas_Button.setText("Registar Resultados");
        GerirEscolas_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerirEscolas_ButtonActionPerformed(evt);
            }
        });

        Logout_Button.setText("Logout");
        Logout_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(Juiz_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Consultar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GerirEscolas_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Juiz_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Consultar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GerirEscolas_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GerirEscolas_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerirEscolas_ButtonActionPerformed
        new RegistarResultados(this.a);
        this.dispose();
    }//GEN-LAST:event_GerirEscolas_ButtonActionPerformed

    private void Consultar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Consultar_ButtonActionPerformed
        new Consultar(this.a);
        this.dispose();
    }//GEN-LAST:event_Consultar_ButtonActionPerformed

    private void Logout_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout_ButtonActionPerformed
       /* new Login(this.a);*/
        this.dispose();
    }//GEN-LAST:event_Logout_ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar_Button;
    private javax.swing.JButton GerirEscolas_Button;
    private javax.swing.JLabel Juiz_Label;
    private javax.swing.JButton Logout_Button;
    // End of variables declaration//GEN-END:variables
}
