/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Competicao.Competicao;
import Competicao.Jogo;
import Competicao.Torneio;
import Gestao.Jogador;
import Gestao.Equipa;
import Gestao.Escola;
import java.util.Collection;
import java.util.HashMap;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Rui
 */
public class RegistarResultados extends javax.swing.JFrame implements Observer{
    private AssociacaoEscolasFutebol a;
    private DefaultListModel modelo1;
    private DefaultListModel modelo2;
    /**
     * Creates new form RegistarResultados
     */
    public RegistarResultados(AssociacaoEscolasFutebol a) {
        this.a = a;
        this.a.addObserver(this);
        initComponents();
        this.setVisible(true);
        Remover_Button.setEnabled(false);
        Adicionar_Button.setEnabled(false);
        RegistarResultado_Button.setEnabled(false);
        Equipa1_RadioButton.setEnabled(false);
        Equipa2_RadioButton.setEnabled(false);
        AutoGolo_CheckBox.setEnabled(false);
        Jogador_ComboBox.setEnabled(false);
        MarcadoresEquipa1_List.setEnabled(false);
        MarcadoresEquipa2_List.setEnabled(false);
        
        Campeonato_RadioButton.doClick();
        
        MarcadoresEquipa1_List.setModel(new DefaultListModel());
        modelo1 = (DefaultListModel) MarcadoresEquipa1_List.getModel();
        
        MarcadoresEquipa2_List.setModel(new DefaultListModel());
        modelo2 = (DefaultListModel) MarcadoresEquipa2_List.getModel();
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Juiz_Label = new javax.swing.JLabel();
        SelecionarCompeticao_Panel = new javax.swing.JPanel();
        Escalao_ComboBox = new javax.swing.JComboBox();
        Competicao_ComboBox = new javax.swing.JComboBox();
        Competicao_Label = new javax.swing.JLabel();
        Escalao_Label = new javax.swing.JLabel();
        Campeonato_RadioButton = new javax.swing.JRadioButton();
        Torneio_RadioButton = new javax.swing.JRadioButton();
        Jornada_ComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        ResultadosPorRegistar_Panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResultadosPorRegistar_List = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Equipa1_Label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        MarcadoresEquipa1_List = new javax.swing.JList();
        Equipa2_Label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        MarcadoresEquipa2_List = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        Equipa1_RadioButton = new javax.swing.JRadioButton();
        Equipa2_RadioButton = new javax.swing.JRadioButton();
        AutoGolo_CheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        Jogador_ComboBox = new javax.swing.JComboBox();
        Adicionar_Button = new javax.swing.JButton();
        Remover_Button = new javax.swing.JButton();
        RegistarResultado_Button = new javax.swing.JButton();
        Golos1_Label = new javax.swing.JLabel();
        Golos2_Label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Associação de Escolas de Futebol - Época 13/14");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(822, 562));

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        Juiz_Label.setFont(new java.awt.Font("Trebuchet MS", 0, 20)); // NOI18N
        Juiz_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Juiz_Label.setText("Registar Resultados:");

        SelecionarCompeticao_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionar Competição"));

        Escalao_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PreEscolaA", "PreEscolaB", "MinisA", "MinisB", "EscolaA", "EscolaB", "InfantisA", "InfantisB", "IniciadosA", "IniciadosB" }));
        Escalao_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Escalao_ComboBoxActionPerformed(evt);
            }
        });

        Competicao_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Competicao_ComboBoxItemStateChanged(evt);
            }
        });

        Competicao_Label.setText("Competição:");

        Escalao_Label.setText("Escalão:");

        buttonGroup2.add(Campeonato_RadioButton);
        Campeonato_RadioButton.setText("Campeonato");
        Campeonato_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Campeonato_RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(Torneio_RadioButton);
        Torneio_RadioButton.setText("Torneio");
        Torneio_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Torneio_RadioButtonActionPerformed(evt);
            }
        });

        Jornada_ComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Jornada_ComboBoxItemStateChanged(evt);
            }
        });

        jLabel4.setText("Jornada:");

        javax.swing.GroupLayout SelecionarCompeticao_PanelLayout = new javax.swing.GroupLayout(SelecionarCompeticao_Panel);
        SelecionarCompeticao_Panel.setLayout(SelecionarCompeticao_PanelLayout);
        SelecionarCompeticao_PanelLayout.setHorizontalGroup(
            SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelecionarCompeticao_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelecionarCompeticao_PanelLayout.createSequentialGroup()
                        .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelecionarCompeticao_PanelLayout.createSequentialGroup()
                                .addComponent(Campeonato_RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(Torneio_RadioButton))
                            .addGroup(SelecionarCompeticao_PanelLayout.createSequentialGroup()
                                .addComponent(Escalao_Label)
                                .addGap(30, 30, 30)
                                .addComponent(Escalao_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelecionarCompeticao_PanelLayout.createSequentialGroup()
                        .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Competicao_Label)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Jornada_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Competicao_ComboBox, 0, 182, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SelecionarCompeticao_PanelLayout.setVerticalGroup(
            SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelecionarCompeticao_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Escalao_Label)
                    .addComponent(Escalao_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Campeonato_RadioButton)
                    .addComponent(Torneio_RadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Competicao_Label)
                    .addComponent(Competicao_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SelecionarCompeticao_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jornada_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        ResultadosPorRegistar_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionar resultado por registar:"));

        ResultadosPorRegistar_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ResultadosPorRegistar_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ResultadosPorRegistar_ListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ResultadosPorRegistar_List);

        javax.swing.GroupLayout ResultadosPorRegistar_PanelLayout = new javax.swing.GroupLayout(ResultadosPorRegistar_Panel);
        ResultadosPorRegistar_Panel.setLayout(ResultadosPorRegistar_PanelLayout);
        ResultadosPorRegistar_PanelLayout.setHorizontalGroup(
            ResultadosPorRegistar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        ResultadosPorRegistar_PanelLayout.setVerticalGroup(
            ResultadosPorRegistar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
        );

        jButton1.setText("Voltar Menu Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado selecionado"));

        Equipa1_Label.setText("Equipa 1");

        MarcadoresEquipa1_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MarcadoresEquipa1_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MarcadoresEquipa1_ListMouseClicked(evt);
            }
        });
        MarcadoresEquipa1_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MarcadoresEquipa1_ListValueChanged(evt);
            }
        });
        MarcadoresEquipa1_List.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MarcadoresEquipa1_ListFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MarcadoresEquipa1_ListFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(MarcadoresEquipa1_List);

        Equipa2_Label.setText("Equipa 2");

        MarcadoresEquipa2_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MarcadoresEquipa2_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                MarcadoresEquipa2_ListValueChanged(evt);
            }
        });
        MarcadoresEquipa2_List.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MarcadoresEquipa2_ListFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MarcadoresEquipa2_ListFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(MarcadoresEquipa2_List);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar/ Remover golo:"));

        buttonGroup1.add(Equipa1_RadioButton);
        Equipa1_RadioButton.setText("Equipa 1");
        Equipa1_RadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Equipa1_RadioButtonStateChanged(evt);
            }
        });
        Equipa1_RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Equipa1_RadioButtonItemStateChanged(evt);
            }
        });
        Equipa1_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipa1_RadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(Equipa2_RadioButton);
        Equipa2_RadioButton.setText("Equipa 2");
        Equipa2_RadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Equipa2_RadioButtonStateChanged(evt);
            }
        });
        Equipa2_RadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Equipa2_RadioButtonItemStateChanged(evt);
            }
        });
        Equipa2_RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equipa2_RadioButtonActionPerformed(evt);
            }
        });

        AutoGolo_CheckBox.setText("Auto Golo?");
        AutoGolo_CheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AutoGolo_CheckBoxStateChanged(evt);
            }
        });
        AutoGolo_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoGolo_CheckBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Jogador:");

        Adicionar_Button.setText("Adicionar Marcador");
        Adicionar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adicionar_ButtonActionPerformed(evt);
            }
        });

        Remover_Button.setText("Remover Marcador");
        Remover_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remover_ButtonActionPerformed(evt);
            }
        });

        RegistarResultado_Button.setText("Registar Resultado");
        RegistarResultado_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarResultado_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistarResultado_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Equipa1_RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(Equipa2_RadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(AutoGolo_CheckBox))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Adicionar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Remover_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Jogador_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Adicionar_Button, Remover_Button});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Equipa1_RadioButton)
                    .addComponent(Equipa2_RadioButton)
                    .addComponent(AutoGolo_CheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Jogador_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Remover_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Adicionar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegistarResultado_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Adicionar_Button, Remover_Button});

        Golos1_Label.setText("0");

        Golos2_Label.setText("0");

        jLabel1.setText("-");

        jLabel2.setText("-");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Equipa1_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Golos1_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Equipa2_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Golos2_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane3, jScrollPane4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Equipa1_Label)
                    .addComponent(Equipa2_Label)
                    .addComponent(Golos1_Label)
                    .addComponent(Golos2_Label)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane3, jScrollPane4});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Juiz_Label)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ResultadosPorRegistar_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SelecionarCompeticao_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(Juiz_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(SelecionarCompeticao_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResultadosPorRegistar_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Juiz(a);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AutoGolo_CheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AutoGolo_CheckBoxStateChanged
        
    }//GEN-LAST:event_AutoGolo_CheckBoxStateChanged

    private void AutoGolo_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoGolo_CheckBoxActionPerformed
        //Atualiza Jogador_ComboBox
        Jogador_ComboBox.removeAllItems();
        if(Equipa1_RadioButton.isSelected()) {
            if(!AutoGolo_CheckBox.isSelected()) {
                Jogador_ComboBox.setEnabled(true);
                String escolaEequipa [] = Equipa1_Label.getText().split("-");
                Escola escola = a.getDAOEscola().get(escolaEequipa[0]);
                Equipa equipa = escola.getEquipa(Equipa1_Label.getText()); 
                Collection<Jogador> jogadores = equipa.getJogadores();
                if (jogadores != null) {
                    for(Jogador jogador: jogadores)
                        Jogador_ComboBox.addItem(jogador.getCodJogador());
                }
            }
            else
                Jogador_ComboBox.setEnabled(false);
        }
        if(Equipa2_RadioButton.isSelected()) {
            if(!AutoGolo_CheckBox.isSelected()) {
                Jogador_ComboBox.setEnabled(true);
                String escolaEequipa [] = Equipa2_Label.getText().split("-");
                Escola escola = a.getDAOEscola().get(escolaEequipa[0]);
                Equipa equipa = escola.getEquipa(Equipa2_Label.getText()); 
                Collection<Jogador> jogadores = equipa.getJogadores();
                if (jogadores != null) {
                    for(Jogador jogador: jogadores)
                        Jogador_ComboBox.addItem(jogador.getCodJogador());
                }
            }
            else
                Jogador_ComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_AutoGolo_CheckBoxActionPerformed

    private void MarcadoresEquipa1_ListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MarcadoresEquipa1_ListFocusGained
        MarcadoresEquipa2_List.clearSelection();
        
    }//GEN-LAST:event_MarcadoresEquipa1_ListFocusGained

    private void MarcadoresEquipa1_ListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MarcadoresEquipa1_ListFocusLost
        Equipa1_RadioButton.setEnabled(false);
        Equipa2_RadioButton.setEnabled(false);
        AutoGolo_CheckBox.setEnabled(false);
        Jogador_ComboBox.setEnabled(false);
        Adicionar_Button.setEnabled(false);
        Remover_Button.setEnabled(true);
    }//GEN-LAST:event_MarcadoresEquipa1_ListFocusLost

    private void Remover_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remover_ButtonActionPerformed
        if(MarcadoresEquipa1_List.hasFocus()){
            //remover golo selecionado
            String golo1 = Golos1_Label.getText();
            Golos1_Label.setText(""+(Integer.parseInt(golo1)+1));
            MarcadoresEquipa1_List.clearSelection();
        }
        if(MarcadoresEquipa2_List.hasFocus()){
            //remover golo selecionado
            String golo2 = Golos2_Label.getText();
            Golos2_Label.setText(""+(Integer.parseInt(golo2)+1));
            MarcadoresEquipa2_List.clearSelection();
        }
        Equipa1_RadioButton.setEnabled(true);
        Equipa2_RadioButton.setEnabled(true);
        AutoGolo_CheckBox.setEnabled(true);
        Jogador_ComboBox.setEnabled(true);
        Adicionar_Button.setEnabled(true);
        Remover_Button.setEnabled(false);
    }//GEN-LAST:event_Remover_ButtonActionPerformed

    private void MarcadoresEquipa2_ListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MarcadoresEquipa2_ListFocusGained
        MarcadoresEquipa1_List.clearSelection();
    }//GEN-LAST:event_MarcadoresEquipa2_ListFocusGained

    private void Equipa1_RadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Equipa1_RadioButtonStateChanged
        
    }//GEN-LAST:event_Equipa1_RadioButtonStateChanged

    private void Equipa2_RadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Equipa2_RadioButtonStateChanged
        
    }//GEN-LAST:event_Equipa2_RadioButtonStateChanged

    private void Equipa1_RadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Equipa1_RadioButtonItemStateChanged
        if(Equipa1_RadioButton.isSelected())
            Jogador_ComboBox.setEnabled(true);
        if(Equipa1_RadioButton.isSelected()== false)
            Jogador_ComboBox.setEnabled(false);
    }//GEN-LAST:event_Equipa1_RadioButtonItemStateChanged

    private void Equipa2_RadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Equipa2_RadioButtonItemStateChanged
        if(Equipa2_RadioButton.isSelected())
            Jogador_ComboBox.setEnabled(true);
        if(Equipa2_RadioButton.isSelected()== false)
            Jogador_ComboBox.setEnabled(false);
    }//GEN-LAST:event_Equipa2_RadioButtonItemStateChanged

    private void MarcadoresEquipa1_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MarcadoresEquipa1_ListValueChanged
        Equipa1_RadioButton.setEnabled(false);
        Equipa2_RadioButton.setEnabled(false);
        AutoGolo_CheckBox.setEnabled(false);
        Jogador_ComboBox.setEnabled(false);
        Adicionar_Button.setEnabled(false);
        Remover_Button.setEnabled(true);
        MarcadoresEquipa2_List.clearSelection();
        Equipa1_RadioButton.setSelected(true);
        RegistarResultado_Button.setEnabled(true);
    }//GEN-LAST:event_MarcadoresEquipa1_ListValueChanged

    private void MarcadoresEquipa2_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_MarcadoresEquipa2_ListValueChanged
        Equipa1_RadioButton.setEnabled(false);
        Equipa2_RadioButton.setEnabled(false);
        AutoGolo_CheckBox.setEnabled(false);
        Jogador_ComboBox.setEnabled(false);
        Adicionar_Button.setEnabled(false);
        Remover_Button.setEnabled(true);
        MarcadoresEquipa1_List.clearSelection();
        Equipa2_RadioButton.setSelected(true);
    }//GEN-LAST:event_MarcadoresEquipa2_ListValueChanged

    private void MarcadoresEquipa2_ListFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MarcadoresEquipa2_ListFocusLost
        Equipa1_RadioButton.setEnabled(false);
        Equipa2_RadioButton.setEnabled(false);
        AutoGolo_CheckBox.setEnabled(false);
        Jogador_ComboBox.setEnabled(false);
        Adicionar_Button.setEnabled(false);
        Remover_Button.setEnabled(true);
    }//GEN-LAST:event_MarcadoresEquipa2_ListFocusLost

    private void MarcadoresEquipa1_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MarcadoresEquipa1_ListMouseClicked
      
    }//GEN-LAST:event_MarcadoresEquipa1_ListMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        MarcadoresEquipa1_List.clearSelection();
        MarcadoresEquipa2_List.clearSelection();
        Equipa1_RadioButton.setEnabled(true);
        Equipa2_RadioButton.setEnabled(true);
        AutoGolo_CheckBox.setEnabled(true);
        Jogador_ComboBox.setEnabled(true);
        Adicionar_Button.setEnabled(true);
        Remover_Button.setEnabled(false);
        RegistarResultado_Button.setEnabled(true);
    }//GEN-LAST:event_jPanel1MousePressed

    private void RegistarResultado_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarResultado_ButtonActionPerformed
        buttonGroup1.clearSelection();
        HashMap<String, Integer> jogadores_1 = new HashMap<String,Integer>();
        HashMap<String, Integer> jogadores_2 = new HashMap<String,Integer>();
        String jogador;
        for (int i=0; i < modelo1.getSize(); i++) {
            jogador = modelo1.getElementAt(i).toString();
            if (!jogador.equals("Auto Golo")) {
                if (jogadores_1.containsKey(jogador))
                    jogadores_1.put(jogador, (jogadores_1.get(jogador)+1));
                else
                    jogadores_1.put(jogador, 1);
            }
        }
        for (int i=0; i < modelo2.getSize(); i++) {
            jogador = modelo2.getElementAt(i).toString();
            if (!jogador.equals("Auto Golo")) {
                if (jogadores_2.containsKey(jogador))
                    jogadores_2.put(jogador, (jogadores_2.get(jogador)+1));
                else
                    jogadores_2.put(jogador, 1);
            }
        }
        String cod_competicao;
        if (Campeonato_RadioButton.isSelected()){
           cod_competicao = "Escalao." + Escalao_ComboBox.getSelectedItem().toString(); 
            try {
            a.SetGolo(cod_competicao, jogadores_1, jogadores_2);
            int Golos1 = Integer.parseInt(Golos1_Label.getText());
            int Golos2 = Integer.parseInt(Golos2_Label.getText());
            String[]cod= ResultadosPorRegistar_List.getSelectedValue().toString().split("-");
            String[] equipas = ResultadosPorRegistar_List.getSelectedValue().toString().split(" vs ");
            String cod_equipa1 = equipas[0];
            String cod_equipa2 = equipas[1];
            a.SetResultado(cod_competicao, cod_competicao+Jornada_ComboBox.getSelectedIndex(),cod_equipa1, cod_equipa2, Golos1, Golos2);
            JOptionPane.showMessageDialog(null, "Resultado registado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        }
            
        else{
            cod_competicao = Competicao_ComboBox.getSelectedItem().toString();
             try {
            a.SetGolo(cod_competicao, jogadores_1, jogadores_2);
            int Golos1 = Integer.parseInt(Golos1_Label.getText());
            int Golos2 = Integer.parseInt(Golos2_Label.getText());
            String[]cod= ResultadosPorRegistar_List.getSelectedValue().toString().split("-");
            String[] equipas = ResultadosPorRegistar_List.getSelectedValue().toString().split(" vs ");
            String cod_equipa1 = equipas[0];
            String cod_equipa2 = equipas[1];
            a.SetResultado(cod_competicao,cod_competicao+"_"+(Jornada_ComboBox.getSelectedIndex()+1),cod_equipa1, cod_equipa2, Golos1, Golos2);
            JOptionPane.showMessageDialog(null, "Resultado registado com sucesso!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
        }
       modelo1.removeAllElements();
        modelo2.removeAllElements();
        atualiza_ResultadosPorRegistar_List();
    }//GEN-LAST:event_RegistarResultado_ButtonActionPerformed

    private void ResultadosPorRegistar_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ResultadosPorRegistar_ListValueChanged
        Equipa1_RadioButton.setEnabled(true);
        Equipa2_RadioButton.setEnabled(true);
        AutoGolo_CheckBox.setEnabled(true);
        Jogador_ComboBox.setEnabled(true);
        Adicionar_Button.setEnabled(true);
        Remover_Button.setEnabled(false);
        RegistarResultado_Button.setEnabled(true);
        MarcadoresEquipa1_List.setEnabled(true);
        MarcadoresEquipa2_List.setEnabled(true);
        
        //Atualiza Equipa1_Label e Equipa2_Label
        String [] equipas;
        if(ResultadosPorRegistar_List.getSelectedIndex()>-1){
            equipas = ResultadosPorRegistar_List.getSelectedValue().toString().split(" vs ");
            Equipa1_Label.setText(equipas[0]);
            Golos1_Label.setText("0");
            Equipa2_Label.setText(equipas[1]);
            Golos2_Label.setText("0");
        }
        //Atualiza MarcadoresEquipa1_List e MarcadoresEquipa2_List
        MarcadoresEquipa1_List.removeAll();
        MarcadoresEquipa2_List.removeAll();
        
        
        //Atualiza Jogador_ComboBox
        buttonGroup1.clearSelection();
        Jogador_ComboBox.removeAllItems();
    }//GEN-LAST:event_ResultadosPorRegistar_ListValueChanged

    private void Adicionar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adicionar_ButtonActionPerformed
        try {
            if(Equipa1_RadioButton.isSelected()) {
                
                if(!AutoGolo_CheckBox.isSelected()) {
                    modelo1.addElement(Jogador_ComboBox.getSelectedItem().toString());
                    String golo1 = Golos1_Label.getText();
                    Golos1_Label.setText(""+(Integer.parseInt(golo1)+1));
                }
                else {
                    modelo1.addElement("Auto Golo");
                    String golo1 = Golos1_Label.getText();
                    Golos1_Label.setText(""+(Integer.parseInt(golo1)+1));
                }
                
            }
            if(Equipa2_RadioButton.isSelected()) {
                if(!AutoGolo_CheckBox.isSelected()) {
                    modelo2.addElement(Jogador_ComboBox.getSelectedItem().toString());
                    String golo2 = Golos2_Label.getText();
                    Golos2_Label.setText(""+(Integer.parseInt(golo2)+1));
                }
                else {
                    modelo2.addElement("Auto Golo");
                    String golo2 = Golos2_Label.getText();
                    Golos2_Label.setText(""+(Integer.parseInt(golo2)+1));
                }
            }
        }
        catch(Exception ex) {
            
        }
    }//GEN-LAST:event_Adicionar_ButtonActionPerformed

    private void Competicao_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Competicao_ComboBoxItemStateChanged
        //Atualiza Jornadas_ComboBox
        Jornada_ComboBox.removeAllItems();
        Competicao competicao;
        int max_jornadas;
        if (Campeonato_RadioButton.isSelected()) {
            String key = "Escalao." + Escalao_ComboBox.getSelectedItem().toString();
            competicao = a.getDAOCompeticao().get(key);
            if(competicao != null) {
                max_jornadas = competicao.getDAOJornada().size(key);
                for (int i=1; i<= max_jornadas; i++)
                    Jornada_ComboBox.addItem(Integer.toString(i));
            }
        }
        if (Torneio_RadioButton.isSelected()) {
            if(Competicao_ComboBox.getSelectedIndex()>-1){
            String key = Competicao_ComboBox.getSelectedItem().toString();
            competicao = a.getDAOCompeticao().get(key);
            if(competicao != null) {
         
                max_jornadas = competicao.getDAOJornada().size(key);
                for (int i=1; i<= max_jornadas; i++)
                    Jornada_ComboBox.addItem(Integer.toString(i));
            }
        }
        }
    
    }//GEN-LAST:event_Competicao_ComboBoxItemStateChanged

    private void Jornada_ComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Jornada_ComboBoxItemStateChanged
        atualiza_ResultadosPorRegistar_List();
        
    }//GEN-LAST:event_Jornada_ComboBoxItemStateChanged

    private void Escalao_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Escalao_ComboBoxActionPerformed
        atualiza_Competicao_ComboBox(); 
    }//GEN-LAST:event_Escalao_ComboBoxActionPerformed

    private void Campeonato_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Campeonato_RadioButtonActionPerformed
        atualiza_Competicao_ComboBox(); 
    }//GEN-LAST:event_Campeonato_RadioButtonActionPerformed

    private void Torneio_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Torneio_RadioButtonActionPerformed
        atualiza_Competicao_ComboBox(); 
    }//GEN-LAST:event_Torneio_RadioButtonActionPerformed

    private void Equipa1_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipa1_RadioButtonActionPerformed
        //Atualiza Jogador_ComboBox
        Jogador_ComboBox.removeAllItems();
        if(!AutoGolo_CheckBox.isSelected()) {
            Jogador_ComboBox.setEnabled(true);
            String escolaEequipa [] = Equipa1_Label.getText().split("-");
            Escola escola = a.getDAOEscola().get(escolaEequipa[0]);
            Equipa equipa = escola.getEquipa(Equipa1_Label.getText()); 
            Collection<Jogador> jogadores = equipa.getJogadores();
            if (jogadores != null) {
                for(Jogador jogador: jogadores)
                    Jogador_ComboBox.addItem(jogador.getCodJogador());
            }
        }
        else
            Jogador_ComboBox.setEnabled(false);
    
    }//GEN-LAST:event_Equipa1_RadioButtonActionPerformed

    private void Equipa2_RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equipa2_RadioButtonActionPerformed
        //Atualiza Jogador_ComboBox
        Jogador_ComboBox.removeAllItems();
        if(!AutoGolo_CheckBox.isSelected()) {
            Jogador_ComboBox.setEnabled(true);
            String escolaEequipa [] = Equipa2_Label.getText().split("-");
            Escola escola = a.getDAOEscola().get(escolaEequipa[0]);
            Equipa equipa = escola.getEquipa(Equipa2_Label.getText()); 
            Collection<Jogador> jogadores = equipa.getJogadores();
            if (jogadores != null) {
                for(Jogador jogador: jogadores)
                    Jogador_ComboBox.addItem(jogador.getCodJogador());
            }
        }
        else
            Jogador_ComboBox.setEnabled(false);
    }//GEN-LAST:event_Equipa2_RadioButtonActionPerformed

    private void atualiza_Competicao_ComboBox() {
        Competicao_ComboBox.removeAllItems();
        String escalao;
        for (Competicao c: a.getDAOCompeticao().values()) {
            escalao = c.getEscalao().getClass().toString();
            if (escalao.equals("class Escalao." + Escalao_ComboBox.getSelectedItem().toString())) {
                if(Campeonato_RadioButton.isSelected() && c.getClass().getName().equals("Competicao.Campeonato")) {
                    Competicao_ComboBox.addItem(c.getNome());
                }
                if(Torneio_RadioButton.isSelected() && (c instanceof Torneio))
                    Competicao_ComboBox.addItem(c.getNome());
            }
        }
    }
    
    private void atualiza_ResultadosPorRegistar_List() {
        Competicao competicao;
        ResultadosPorRegistar_List.setModel(new DefaultListModel());
        DefaultListModel modelo = (DefaultListModel) ResultadosPorRegistar_List.getModel();
        
        if (Campeonato_RadioButton.isSelected()) {
            competicao = a.getDAOCompeticao().get("Escalao." + Escalao_ComboBox.getSelectedItem().toString());
            if(competicao != null) {
                String cod_jornada = competicao.getCod_competicao() + Jornada_ComboBox.getSelectedIndex();
                String cod_competicao = "Escalao." + Escalao_ComboBox.getSelectedItem().toString();
                Collection<Jogo> jogos = competicao.getJogos().
                        values(cod_competicao, cod_jornada);
                if(jogos != null) {
                    for(Jogo jogo: jogos) {
                        if (jogo.getGolo1()== -1 || jogo.getGolo2()== -1) {
                            String jogoString = jogo.getEquipa1() + " vs " + jogo.getEquipa2();
                            modelo.addElement(jogoString);
                        }
                    }
                }
            }
        }
        if (Torneio_RadioButton.isSelected()) {
            if(Competicao_ComboBox.getSelectedIndex()>-1){
                competicao = a.getDAOCompeticao().get(Competicao_ComboBox.getSelectedItem().toString());
                if(competicao != null) {
                    String cod_jornada = competicao.getCod_competicao()+"_"+(Jornada_ComboBox.getSelectedIndex()+1);
                    String cod_competicao = Competicao_ComboBox.getSelectedItem().toString();
                    Collection<Jogo> jogos = competicao.getJogos().
                            values(cod_competicao, cod_jornada);
                    if(jogos != null) {
                        for(Jogo jogo: jogos) {
                            if (jogo.getGolo1()== -1 || jogo.getGolo2()== -1) {
                                String jogoString =jogo.getEquipa1() + " vs " + jogo.getEquipa2();
                                modelo.addElement(jogoString);
                            }
                        }
                    }
                }
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar_Button;
    private javax.swing.JCheckBox AutoGolo_CheckBox;
    private javax.swing.JRadioButton Campeonato_RadioButton;
    private javax.swing.JComboBox Competicao_ComboBox;
    private javax.swing.JLabel Competicao_Label;
    private javax.swing.JLabel Equipa1_Label;
    private javax.swing.JRadioButton Equipa1_RadioButton;
    private javax.swing.JLabel Equipa2_Label;
    private javax.swing.JRadioButton Equipa2_RadioButton;
    private javax.swing.JComboBox Escalao_ComboBox;
    private javax.swing.JLabel Escalao_Label;
    private javax.swing.JLabel Golos1_Label;
    private javax.swing.JLabel Golos2_Label;
    private javax.swing.JComboBox Jogador_ComboBox;
    private javax.swing.JComboBox Jornada_ComboBox;
    private javax.swing.JLabel Juiz_Label;
    private javax.swing.JList MarcadoresEquipa1_List;
    private javax.swing.JList MarcadoresEquipa2_List;
    private javax.swing.JButton RegistarResultado_Button;
    private javax.swing.JButton Remover_Button;
    private javax.swing.JList ResultadosPorRegistar_List;
    private javax.swing.JPanel ResultadosPorRegistar_Panel;
    private javax.swing.JPanel SelecionarCompeticao_Panel;
    private javax.swing.JRadioButton Torneio_RadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
